### ISSUE TITLE
Import CAD model into MoveIt! with Docker

### ISSUE THREAD

**Issue by clmoro** [karimsiala/UR-Sim-MoveIt2#1]
Hi,

Thank you very much for this very  helpful tutorial! I was able to use your docker file and to launch straight forward the URSim controlling the robot using MoveIt!. 

Now, I would like to import a CAD file of a mechanical part in MoveIt! together with the robot model, do you have any ideas on how I can do it? Should I modify the Dockerfile?

Thanks a lot!
Angelo

**Comment by karimsiala** [comment]
Hi Angelo,

Thank you so much for your kind words. I genuinely glad that your found it helpful.

However to import a CAD file into MoveIt along with the robot model, you would first need to edit the URDF file being loaded through the launch file [ur_moveit.launch.py](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/humble/ur_moveit_config/launch/ur_moveit.launch.py) from `ur_moveit_config` package.

A couple of step will also be necessary such as converting the meshes of the CAD model to STL or Collada format for example but I'm unfortunately not too familiarized with it.

Thank you again and good luck, ROS can sometimes be too challenging but rewarding at the end for sure.

Let me know if I can assist you further.
Karim

**Comment by clmoro** [comment]
I converted the .step file into a .stl one as you suggested and then imported it in MoveIt! through the GUI, it worked. I`ll try in the next days using the URDF file. 

Thank you very much again!
Angelo

**Comment by karimsiala** [comment]
Glad to hear that. Thank you for the update
I'll close the issue for now but feel free to reach out if you need anything else!
